
// USER REDUCEER TYPES
export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";
export const DONE = "DONE";
export const REFRESH = "REFRESH"